---
# This playbook writes manifest files for the JupyterHub deployment

- name: Install pip for system Python
  yum: name=python-pip state=latest

- name: Install docker-py for the system Python
  pip: name=docker-py state=latest

- name: Create build directory for hub container image
  file: path=/root/docker_images/hub state=directory

- name: Install build files for hub container image
  template: src=templates/{{ item.src }} dest=/root/docker_images/hub/{{ item.dest }}
  with_items:
    - { src: "Dockerfile_hub.j2", dest: "Dockerfile" }
    - { src: "jupyterhub_config.py.j2", dest: "jupyterhub_config.py" }

- name: Log in to Docker Hub
  docker_login:
    username: "{{ dockerhub_username }}"
    email: "{{ dockerhub_email }}"
    password: "{{ dockerhub_password }}"

- name: Build hub container image and push to Docker Hub
  docker_image:
    name: "{{ hub_container_name }}"
    path: /root/docker_images/hub
    tag: "{{ hub_container_tag }}"
    push: yes

- name: Write Kubernetes manifest files
  template: src=templates/jupyterhub-k8s-manifest.yml.j2 dest=/root/jupyterhub-k8s-manifest.yml
