---

- name: Make kube config directory
  file: path=/root/.kube state=directory

# We do this by copying kubectl and the admin.conf from the kube-master
- name: Upload kubectl and Kubernetes config
  copy:
    src: "{{ playbook_dir }}/.artifacts/{{ artifact_namespace }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: kubectl, dest: /usr/local/bin/kubectl, mode: "u=rwx,g=rx,o=rx" }
    - { src: kubernetes-admin.conf, dest: /root/.kube/config, mode: "u=rw,g=,o=" }

- name: Install jq
  apt: name=jq state=latest

- name: Install nginx
  apt: name=nginx state=latest
  notify:
    - Restart nginx

- name: Create nginx certificate directory
  file: path=/etc/nginx/certs state=directory

- name: Create nginx tcpconf.d directory
  file: path=/etc/nginx/tcpconf.d state=directory

- name: Install main nginx configuration
  copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: Remove default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Restart nginx

- name: Ensure nginx starts at boot time
  service: name=nginx enabled=yes

- include: nginx-jupyterhub.yml
