---

- name: Make kube config directory
  file: path=/root/.kube state=directory

# We do this by copying kubectl and the admin.conf from the kube-master
- name: Upload kubectl and Kubernetes config
  copy:
    src: "{{ playbook_dir }}/.artifacts/{{ artifact_namespace }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: kubectl, dest: /usr/local/bin/kubectl, mode: "u=rwx,g=rx,o=rx" }
    - { src: kubernetes-admin.conf, dest: /root/.kube/config, mode: "u=rw,g=,o=" }

- name: Install jq
  apt: name=jq state=latest

- include: nginx-install-main.yml

- name: Create dashboard-users password file
  shell: echo "admin:$(openssl passwd -crypt {{ dashboard_password }})" > /etc/nginx/dashboard-users

- name: Set permissions for dashboard-users password file
  file: path=/etc/nginx/dashboard-users owner=www-data group=www-data mode="u=r,g=,o="

- include: nginx-install-proxy.yml  service={{ item }}
  with_items:
    - { name: jupyterhub, namespace: default, port: 443, basic_auth: false }
    - { name: monitoring-grafana, namespace: kube-system, port: 8001, basic_auth: false }
    - { name: kubernetes-dashboard, namespace: kube-system, port: 8002, basic_auth: true }
