---

- name: Make kube config directory
  file: path=/root/.kube state=directory

# We do this by copying kubectl and the admin.conf from the kube-master
- name: Configure kubectl
  shell: scp -oStrictHostKeyChecking=no {{ groups['kube_masters'][0] }}:{{ item.src }} {{ item.dest }}
  args:
    creates: "{{ item.dest }}"
  with_items:
    - { src: /usr/bin/kubectl, dest: /usr/local/bin/kubectl }
    - { src: /etc/kubernetes/admin.conf, dest: /root/.kube/config }

- name: Install jq
  apt: name=jq state=latest

- include: nginx-install-main.yml

- name: Create dashboard-users password file
  shell: echo "admin:$(openssl passwd -crypt {{ k8s_dashboard_passwd }})" > /etc/nginx/dashboard-users

- name: Set permissions for dashboard-users password file
  file: path=/etc/nginx/dashboard-users owner=www-data group=www-data mode="u=r,g=,o="

- include: nginx-install-proxy.yml  service={{ item }}
  with_items:
    - { name: jupyterhub, namespace: default, port: 443, basic_auth: false }
    - { name: monitoring-grafana, namespace: kube-system, port: 8001, basic_auth: false }
    - { name: kubernetes-dashboard, namespace: kube-system, port: 8002, basic_auth: true }
