---

- name: Get NodePort
  shell: kubectl get svc/{{ service.name }} -n {{ service.namespace }} -o json | jq '.spec.ports[0].nodePort'
  register: nodeport

- name: Write proxy site config
  template: src=proxy.nginx.conf dest=/etc/nginx/sites-enabled/{{ service.name }}
  vars:
    proxy_to: "http://{{ kube_master_ip }}:{{ nodeport.stdout }}"
  notify:
    - Restart nginx
