---

- name: Add apt repository key for Kubernetes repo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Install Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Install Docker and Kubernetes
  apt: update_cache=yes name={{ item }} state=latest
  with_items:
    - jq
    - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Initialise Kubernetes control plane components
  command: kubeadm init --token={{ kubeadm_token }} --api-advertise-addresses={{ kube_master_ip }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: kubeadm_init
  when: inventory_hostname in groups['kube_masters']

- name: Update proxy-mode for proxy pods
  shell: "kubectl -n kube-system get ds -l 'component=kube-proxy' -o json | jq '.items[0].spec.template.spec.containers[0].command |= .+ [\"--proxy-mode=userspace\"]' | kubectl apply -f - && kubectl -n kube-system delete pods -l 'component=kube-proxy'"
  when: kubeadm_init|changed and inventory_hostname in groups['kube_masters']

- name: Join Kubernetes cluster (preflight checks skipped due to https://github.com/kubernetes/kubeadm/issues/6)
  command: kubeadm join --skip-preflight-checks --token={{ kubeadm_token }} {{ kube_master_ip }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: inventory_hostname in groups['kube_nodes']

- name: Install pod network
  command: kubectl apply -f https://git.io/weave-kube
  when: inventory_hostname in groups['kube_masters']

- name: Ensure kube-dns has started
  shell: kubectl get pods -l k8s-app=kube-dns -n kube-system -o json | jq '.items | map(.status.containerStatuses) | flatten | map(.ready) | any'
  register: result
  until: result.stdout == "true"
  retries: 30
  delay: 10
  when: inventory_hostname in groups['kube_masters']
