---
# This role performs tasks common to all hosts in a Kubernetes cluster

- name: Install NFS utils
  apt: update_cache=yes name=nfs-common state=latest

- name: Remove hostname <-> 127.0.0.1 mapping from /etc/hosts
  lineinfile: >
    dest=/etc/hosts
    regexp="127\.0\.0\.1.*{{ inventory_hostname }}"
    state=absent

- name: Add cluster IPs on correct interface to /etc/hosts
  blockinfile:
    dest: /etc/hosts
    block: |
      {{ hostvars[item]['ansible_' + cluster_interface]['ipv4']['address'] }} {{ item }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    insertbefore: BOF
  with_items: "{{ groups['kube_hosts'] }}"

- name: Add apt repository key for Kubernetes repo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Install Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Install Docker and Kubernetes
  apt: update_cache=yes name={{ item }} state=latest
  with_items:
    - jq
    - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Initialise Kubernetes control plane components
  command: kubeadm init --token={{ kubeadm_token }} --api-advertise-addresses={{ kube_master_ip }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: kubeadm_init
  when: kube_role == 'master'

- name: Correct the API advertise address
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-apiserver.json
    regexp: "--advertise-address"
    line: "          \"--advertise-address={{ kube_master_ip }}\","
    insertafter: "--allow-privileged"
  when: kubeadm_init|changed and kube_role == 'master'

- name: Update proxy-mode for proxy pods
  shell: "kubectl -n kube-system get ds -l 'component=kube-proxy' -o json | jq '.items[0].spec.template.spec.containers[0].command |= .+ [\"--proxy-mode=userspace\"]' | kubectl apply -f - && kubectl -n kube-system delete pods -l 'component=kube-proxy'"
  when: kubeadm_init|changed and kube_role == 'master'

- name: Join Kubernetes cluster (preflight checks skipped due to https://github.com/kubernetes/kubeadm/issues/6)
  command: kubeadm join --skip-preflight-checks --token={{ kubeadm_token }} {{ kube_master_ip }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: kube_role == 'node'

- name: Install pod network
  command: kubectl apply -f https://git.io/weave-kube
  when: kube_role == 'master'

- name: Install Kubernetes Dashboard
  command: kubectl apply -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
  when: kube_role == 'master'
