apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
    jupyterhub: hub-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
  selector:
    jupyterhub: hub-service
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-state
  annotations:
    volume.beta.kubernetes.io/storage-class: "notebook-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: public-notebooks
  annotations:
    volume.beta.kubernetes.io/storage-class: "notebook-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
  labels:
    app: jupyterhub
data:
  jupyterhub-config.py: |-
    import os
    c.JupyterHub.cookie_secret_file = '/var/run/jupyterhub/cookie_secret'
    c.JupyterHub.db_url = '/var/run/jupyterhub/jupyterhub.sqlite'
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    c.KubeSpawner.namespace = os.environ.get('POD_NAMESPACE', 'default')
    c.KubeSpawner.start_timeout = 60 * 5  # Upto 5 minutes, first pulls can be really slow
    c.KubeSpawner.hub_connect_ip = os.environ['JUPYTERHUB_SERVICE_HOST']
    c.KubeSpawner.hub_connect_port = int(os.environ['JUPYTERHUB_SERVICE_PORT'])
    c.KubeSpawner.singleuser_image_spec = '{{ singleuser_image }}'
    # Each user gets their own persistentVolumeClaim
    c.KubeSpawner.pvc_name_template = 'claim-{username}-{userid}'
    c.KubeSpawner.user_storage_capacity = '1Gi'
    c.KubeSpawner.user_storage_class = 'notebook-storage'
    c.KubeSpawner.volumes = [
        {
            'name' : 'notebook-volume',
            'persistentVolumeClaim' : {
                'claimName' : 'claim-{username}-{userid}',
            },
        },
        {
            'name' : 'public-notebook-volume',
            'persistentVolumeClaim' : {
                'claimName' : 'public-notebooks',
            },
        },
    ]
    c.KubeSpawner.volume_mounts = [
        {
            'name' : 'notebook-volume',
            'mountPath' : '/home/jovyan/work',
        },
        {
            'name' : 'public-notebook-volume',
            'mountPath' : '/home/jovyan/work/public',
        },
    ]
{% if ceda_oauth_client_id is defined %}
    c.JupyterHub.authenticator_class = 'jupyterhub_ceda_auth.CedaOAuthenticator'
    c.CedaOAuthenticator.oauth_callback_url = 'https://{{ server_name }}/hub/oauth_callback'
    c.CedaOAuthenticator.client_id = os.environ['CEDA_OAUTH_CLIENT_ID']
    c.CedaOAuthenticator.client_secret = os.environ['CEDA_OAUTH_CLIENT_SECRET']
{% else %}
    c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
{% endif %}
    # To begin with, the whitelist is just the admin users
    c.Authenticator.admin_users = { {% for user in jupyterhub_admins %}'{{ user }}',{% endfor %} }
    c.Authenticator.whitelist = { {% for user in jupyterhub_admins %}'{{ user }}',{% endfor %} }
    c.JupyterHub.admin_access = True
---
{% if ceda_oauth_client_id is defined %}
apiVersion: v1
kind: Secret
metadata:
  name: ceda-oauth-creds
  labels:
    app: jupyterhub
type: Opaque
data:
  client_id: {{ ceda_oauth_client_id|b64encode }}
  client_secret: {{ ceda_oauth_client_secret|b64encode }}
---
{% endif %}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
    jupyterhub: hub-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub
        jupyterhub: hub-service
    spec:
      containers:
        - name: jupyterhub
          image: {{ jupyterhub_image }}
          command:
            - jupyterhub
            - --config
            - /srv/jupyterhub/conf/jupyterhub_config.py
            - --no-ssl
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SINGLEUSER_IMAGE
              value: {{ singleuser_image }}
{% if ceda_oauth_client_id is defined %}
            - name: CEDA_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ceda-oauth-creds
                  key: client_id
            - name: CEDA_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ceda-oauth-creds
                  key: client_secret
{% endif %}
          ports:
            - name: proxy
              containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /srv/jupyterhub/conf/
            - name: state-volume
              mountPath: /var/run/jupyterhub
      volumes:
        - name: config-volume
          configMap:
            name: jupyterhub-config
            items:
              - key: jupyterhub-config.py
                path: jupyterhub_config.py
        - name: state-volume
          persistentVolumeClaim:
            claimName: jupyterhub-state
