kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: notebook-storage
  labels:
    app: jupyterhub
    jupyterhub: notebook-storage
provisioner: kubernetes-incubator/nfs-provisioner
