apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: monitoring-storage
  namespace: kube-system
  labels:
    app: monitoring
provisioner: kubernetes-incubator/nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-storage
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "monitoring-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "monitoring-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
