kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nfs-server
spec:
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        storagenode: nfs
      hostNetwork: true
      containers:
        - name: nfs-server
          image: {{ nfs_server_image }}
          ports:
            - name: nfs
              containerPort: 2049
              hostPort: 2049
            - name: mountd
              containerPort: 20048
              hostPort: 20048
            - name: rpcbind
              containerPort: 111
              hostPort: 111
            - name: rpcbind-udp
              containerPort: 111
              hostPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
          volumeMounts:
            - name: export-volume
              mountPath: /exports
      volumes:
        - name: export-volume
          hostPath:
            path: /srv/nfs_share
