---
# Tasks for setting up an NFS server

- name: Install NFS server
  yum: name=nfs-utils state=latest

- name: Ensure NFS server is started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap

- name: Create directory for export
  file: path=/srv/nfsshare state=directory mode="u=rwx,g=rwx,o=rwx"

- name: Configure NFS exports
  blockinfile:
    dest: /etc/exports
    content: |
      /srv/nfsshare  *(rw,sync,no_root_squash)
  notify:
    - Restart nfs-server
