kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
spec:
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      nodeSelector:
        storagenode: nfs
      hostNetwork: true
      containers:
        - name: nfs-provisioner
          image: {{ nfs_provisioner_image }}:{{ nfs_provisioner_version }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: nfs
              containerPort: 2049
              hostPort: 2049
            - name: mountd
              containerPort: 20048
              hostPort: 20048
            - name: rpcbind
              containerPort: 111
              hostPort: 111
            - name: rpcbind-udp
              containerPort: 111
              hostPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
          args:
            - "-provisioner=kubernetes-incubator/nfs-provisioner"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /data
