---

- name: Create manifests directory
  file: path=/root/manifests state=directory

- name: Copy k8s manifest files
  template: src={{ item }} dest=/root/manifests/ mode="u=rw,g=,o="
  with_items:
    - monitoring-storage.yml
    - elasticsearch.yml
    - fluentd.yml
    - kibana.yml
    - influxdb.yml
    - heapster.yml
    - grafana.yml

- name: Install k8s manifests
  shell: kubectl apply -f {{ item }} --force
  with_items:
    - /root/manifests/monitoring-storage.yml
    - /root/manifests/elasticsearch.yml
    - /root/manifests/fluentd.yml
    - /root/manifests/kibana.yml
    - /root/manifests/influxdb.yml
    - /root/manifests/heapster.yml
    - /root/manifests/grafana.yml
    - https://git.io/kube-dashboard

- name: Ensure monitoring tools have started
  shell: kubectl get pods -l {{ item }} -n kube-system -o json | jq '.items | map(.status.containerStatuses) | flatten | map(.ready) | all'
  register: result
  until: result.stdout == "true"
  retries: 30
  delay: 10
  with_items:
    - "k8s-app=elasticsearch-logging"
    - "k8s-app=fluentd-es"
    - "k8s-app=kibana-logging"
    - "k8s-app=influxdb"
    - "k8s-app=heapster"
    - "k8s-app=grafana"
    - "app=kubernetes-dashboard"
