---

# Force fact-caching for all hosts
- hosts: all
  tasks: []

- hosts: kube_hosts
  remote_user: root
  force_handlers: yes
  roles:
    - jupyterhub_k8s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
