---
# This playbook sets up a Kubernetes cluster with supporting NFS server for
# persistent storage

- hosts: nfs_servers
  remote_user: root
  force_handlers: yes
  roles:
    - nfs_server

- hosts: kube_hosts
  remote_user: root
  force_handlers: yes
  roles:
    - kubernetes

- hosts: kube_masters
  remote_user: root
  force_handlers: yes
  roles:
    - jupyterhub_k8s
  vars_files:
    - dockerhub_credentials.yml
