---

- name: Install jq on master
  apt: update_cache=yes name=jq state=latest
  when: inventory_hostname in groups['kube_masters']

- name: Install pip for system Python
  apt: update_cache=yes name=python-pip state=latest

- name: Install docker-py
  pip: name=docker-py state=latest

- name: Pre-pull notebook image onto nodes
  docker_image: name={{ singleuser_image }}
  when: inventory_hostname in groups['kube_nodes']

- name: Get heketi service endpoint
  shell: kubectl describe svc/heketi | grep "Endpoints:" | awk '{print $2}'
  register: heketi_svc_ep
  when: inventory_hostname in groups['kube_masters']

- name: Set heketi_svc_url fact
  set_fact:
    heketi_svc_url: http://{{ heketi_svc_ep.stdout }}
  when: inventory_hostname in groups['kube_masters']

- name: Create manifests directory
  file: path=/root/manifests state=directory
  when: inventory_hostname in groups['kube_masters']

- name: Copy k8s manifest files
  template: src={{ item }} dest=/root/manifests/ mode="u=rw,g=,o="
  with_items:
    - glusterfs-storageclass.yml
    - hub-service.yml
  when: inventory_hostname in groups['kube_masters']

- name: Install k8s manifests
  shell: kubectl apply -f /root/manifests/{{ item }} --force
  with_items:
    - glusterfs-storageclass.yml
    - hub-service.yml
  when: inventory_hostname in groups['kube_masters']

- name: Ensure all jupyterhub containers have started
  shell: kubectl get pods -l app=jupyterhub -o json | jq '.items | map(.status.containerStatuses) | flatten | map(.ready) | all'
  register: result
  until: result.stdout == "true"
  retries: 30
  delay: 10
  when: inventory_hostname in groups['kube_masters']
