---

- name: Install jq on master
  apt: update_cache=yes name=jq state=latest
  when: inventory_hostname in groups['kube_masters']

- name: Install NFS client utils on all nodes
  apt: update_cache=yes name=nfs-common state=latest
  when: inventory_hostname in groups['kube_nodes']

- name: Check if storage device has been partitioned
  stat: path={{ storage_partition }}
  register: stat
  when: inventory_hostname in groups['nfs_nodes']

- name: Make primary partition on storage device
  shell: parted -s -a opt {{ storage_device }} mklabel gpt -- mkpart primary ext4 1 -1
  when: inventory_hostname in groups['nfs_nodes'] and not stat.stat.exists

- name: Create filesystem on primary partition
  filesystem:
    dev: "{{ storage_partition }}"
    fstype: ext4
    resizefs: yes
  when: inventory_hostname in groups['nfs_nodes']

- name: Mount storage device
  mount:
    name: /srv/nfs_share
    src: "{{ storage_device }}1"
    state: mounted
    fstype: ext4
  when: inventory_hostname in groups['nfs_nodes']

- name: Ensure rpcbind started
  service: name=rpcbind state=started enabled=yes
  when: inventory_hostname in groups['nfs_nodes']

- name: Label storage nodes
  shell: kubectl label node {{ item }} storagenode=nfs --overwrite=true
  with_items: "{{ groups['nfs_nodes'] }}"
  when: inventory_hostname in groups['kube_masters']

- name: Create manifests directory
  file: path=/root/manifests state=directory
  when: inventory_hostname in groups['kube_masters']

- name: Copy nfs-daemonset.yml to master
  template:
    src: nfs-daemonset.yml
    dest: /root/manifests
    mode: u=rw,g=,o=
  when: inventory_hostname in groups['kube_masters']

- name: Install NFS daemonset
  shell: kubectl apply -f /root/manifests/nfs-daemonset.yml --force=true
  when: inventory_hostname in groups['kube_masters']

- name: Ensure NFS daemonset is running
  shell: kubectl get ds/nfs-server -o json | jq '.status.numberReady == .status.desiredNumberScheduled'
  register: result
  until: result.stdout == "true"
  retries: 30
  delay: 10
  when: inventory_hostname in groups['kube_masters']
